[package]
name = "log_collection"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.42.0"
bytes = "1.10.1"
clap = { version = "4.5.40", features = ["derive", "string"] }
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
