name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Init database
      run: apt install sqlite3 -y && sqlite3 message.db < migrations/message.sql
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
