name: Test package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download sqlx CLI tool for sqlite
      run: cargo install sqlx-cli --features sqlite
    - name: Setup test database 
      run: sqlx db setup
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
