name: Test package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Init message table
      run: sqlite3 message.db < migrations/message.sql
    - name: Init user table
      run: sqlite3 message.db < migrations/user.sql
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
